name: Build and deploy Furry Index (EVALUATION)

on:
  push:
    branches:
      - evaluation

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    permissions:
      contents: read
      packages: write
      attestations: write
      id-token: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Log in to GitHub Docker Registry
        run: echo "${{ secrets.GITHUB_TOKEN }}" | docker login ghcr.io -u ${{ github.actor }} --password-stdin

      - name: Build Docker image
        run: |
          IMAGE_NAME=ghcr.io/${{ github.repository }}:evaluation
          IMAGE_NAME=${IMAGE_NAME,,}
          docker build -t $IMAGE_NAME .
          echo "IMAGE_NAME=$IMAGE_NAME" >> $GITHUB_ENV

      - name: Push Docker image
        run: docker push $IMAGE_NAME

  remote-deploy:
    runs-on: ubuntu-latest

    needs: build-and-push

    env:
      ENVIROMENT: "EVAL"
      FIPORT: "4100"
      PGPORT: "11000"

    steps:
      - name: Checkout (again for copying compose file)
        uses: actions/checkout@v3

      - name: Generate .env
        run: |
          echo "ENVIROMENT=${ENVIROMENT}" > .env
          echo "BUILDLNK=ghcr.io/${{ github.repository }}:evaluation" >> .env
          echo "PGPORT=${PGPORT}" >> .env
          echo "FIPORT=${FIPORT}" >> .env

      - name: Setup SSH agent
        uses: webfactory/ssh-agent@v0.9.0
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

      - name: Setup SSH
        uses: webfactory/ssh-agent@v0.9.0
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

      - name: Copy compose + .env via scp
        run: |
          scp -o StrictHostKeyChecking=no \
            docker-compose.yml .env \
            ${{ secrets.REMOTE_USER }}@${{ secrets.REMOTE_HOST }}:${{ secrets.REMOTE_PATH }}/

      - name: Deploy on remote server
        run: |
          ssh -o StrictHostKeyChecking=no ${{ secrets.REMOTE_USER }}@${{ secrets.REMOTE_HOST }} << 'EOF'
            cd ${{ secrets.REMOTE_PATH }}
            docker compose pull
            docker compose up -d
          EOF
