name: "EVAL deployment verification"

on:
  pull_request:
    branches:
      - main
      - evaluation
    types: [opened, synchronize, reopened]

jobs:
  health-check:
    runs-on: ubuntu-latest

    steps:
      - name: Wait for response
        run: |
          URL="https://furry-index-eval.vmtech.services/api/whatisthisbuild"
          max_attempts=30
          attempt=1
          interval=1
  
          while true; do
            echo "Attempt $attempt / $max_attempts"
            status=$(curl --silent --output /dev/null --write-out "%{http_code}" "$URL" || true)
            if [ "$status" = "200" ]; then
              echo "Remote service started succesfully."
              break
            fi
  
            if [ "$attempt" -ge "$max_attempts" ]; then
              echo "Remote service returned error. Last status = $status"
              exit 1
            fi
  
            attempt=$(( attempt + 1 ))
            sleep $interval
          done